### ISSUE TITLE
CPU going up 30%

### ISSUE THREAD

**Issue by Sohkka** [arveoncode/relink-damage#32]
Something i've notice when i start using the web app is that my CPU goes up like 30-35% out of nowhere and when the app lose focus this % goes down to normal, this has been tested on

Chrome
Brave
Opera
Edge

https://github.com/arveoncode/relink-damage/assets/54333463/09698551-ccb7-4c92-930a-fc029caaba1e

**Comment by arveoncode** [comment]
Thank you so much for raising this - found the cause of the issue: the background animation is the culprit to the high CPU usage. I've added a toggle on the settings to turn the background on and off, it's on by default, but you can turn it off, and that setting will persist on your local storage.
