### ISSUE TITLE
Feature Request: Add Katalina Warpath partywide Enhanced DMG buff from SBA as toggle

### ISSUE THREAD

**Issue by DarxZalor** [arveoncode/relink-damage#35]
Currently not a part of Maygi's calculator but would be nice to have.

**Comment by arveoncode** [comment]
I'm not entirely sure of the behavior of enhanced damage when it comes from other party members --- does Katalina's partywide Enhanced DMG buff stack with other sources of the buff? Or does the buff with the higher benefit override the other buffs?

**Comment by DarxZalor** [comment]
It'd probably we wise to keep an eye on this if anything changes in a future patch but I was able to gather the following from a pin in the GBFR discord and it looks like any characters with the same type of buff get overridden while it stacks with characters that have their warpath passively increase damage:

Captain: 10% Enhance passive (ele lvls) -> full 25% bonus
Rackam: 20% Enhance buff --> overwritten for 5% extra
Io: 15% Enhance buff --> overwritten for 10% extra
Eugen: 25% Enhance (Charge Attacks and Grenates) --> full 25% bonus
Rosetta: 100% Enhance passive (Rose attacks) --> full 25% bonus
Charlotta: 10% Enhance passive (Noble Stance attacks) --> full 25% bonus
Ghandagoza: 100% Enhance passive (Raging Fist) --> full 25% bonus
Ferry: 15% Enhance buff --> overwritten for 10% extra
Narmaya: 15% Enhance buff --> overwritten for 10% extra (note that this seems to be buggy and somewhat stacks in version 1.2.1)
Lancelot: 10% Enhance buff --> overwritten for 15% extra
Vane: 30% Enhance passive (Y attacks) --> full 25% bonus
Percival: 50% Enhance passive (Schlacht) --> full 25% bonus
Siegfried: 40% Enhance passive (Perfect hits) --> full 25% bonus
Cagliostro: 10%/15% Enhance buff --> overwritten for 15%/10% extra
Yodarha: 30% Enhance passive (Sharpened Focus Combos) --> full 25% bonus
Zeta: 15% Enhance passive (Arvess targets) --> full 25% bonus
Vaseraga: 30% Enhance buff --> no bonus no benefit at all
Seofon: 20% Enhance buff --> overwritten for 10% extra
Tweyen: 10% Enhance buff --> overwritten for 15% extra
Id: 10% Enhance buff--> overwritten for 15% extra

the better list, who gains what bonus:
25% bonus: Captain, Eugen, Rosetta, Charlotta, Ghandagoza, Vane, Percival, Siegfried, Yodarha, Zeta
15% bonus: Lancelot, Cagliostro*, Tweyen, Id
10% bonus: Io, Ferry, Narmaya, Cagliostro, Seofon
5% bonus: Rackam
0% bonus: Vaseraga

Note: Katalina's buff bonus is additive with passive bonuses 


I'm familiar with how Charlotta works so I know that the noble lunge cap is around 340k with all current damage cap options available plus Warpath (307k without Warpath) and with Katalina's buff this goes to 417k which aligns with what is described above.

**Comment by arveoncode** [comment]
I've added a manual input for an enhanced DMG modifier on the "Other Inputs". There is a button that adds the buff based on the selected character that augments the enhanced DMG modifier as per the list you provided.
![image](https://github.com/arveoncode/relink-damage/assets/60457767/4f2f794c-fd0b-49cd-9a14-b2b1fb5675b0)

**Comment by DarxZalor** [comment]
Works for Charlotta at least! Thanks!

I'll let the other experts on other characters let you know if anything is wrong. 😃

**Comment by arveoncode** [comment]
I'll leave this Github Issue open just in case someone finds anything wrong with it 😊
