### ISSUE TITLE
Charlotta Warpath not working

### ISSUE THREAD

**Issue by DarxZalor** [arveoncode/relink-damage#36]

**Comment by arveoncode** [comment]
I've added Charlotta's 10% enhanced dmg to all skill modifiers with the "In Noble Stance" substring, but I'm not sure if that's the entirety of the buff. Please check the application if the calculations seem correct 😅

**Comment by DarxZalor** [comment]
Checked against Maygi's calc and in-game. It looks correct except under Basic Attack -> Continuous attacks the value (assuming all damage caps and warpath) should increase from 54088 to 59495 (or 59497 with Maygi's calc but the difference is small enough that it doesn't matter).

**Comment by arveoncode** [comment]
Fixed Charlotta's calculations now! Please check again 😅 Application wasn't computing all affected Charlotta's skills due to addition of "Sp" skill classification not being implemented after the patch.

**Comment by DarxZalor** [comment]
Looks good! Thanks!

**Comment by arveoncode** [comment]
Closing this issue now, thank you so much!!!
