### ISSUE TITLE
Charged attack DMG sigil does not show bonus.

### ISSUE THREAD

**Issue by Fantsies** [arveoncode/relink-damage#41]
![image](https://github.com/arveoncode/relink-damage/assets/116236243/23da5c46-8d71-4ff7-b88f-0a9753623c81)
As above. (edited)

**Comment by Fantsies** [comment]
Sorry I made sth wrong. The damage calculation is right, just the sigil's bonus is not shown. However Ghandagoza's awakening sigil makes him alwals crit when his rage is 10, that's not calculated so the average damage had some problem before manually fix it.

**Comment by arveoncode** [comment]
Wait you're right, the Charged Attack DMG is not showing up and not being properly calculated --- please check again and confirm if it's fixed
